name: Create video

jobs:
  upload-videos-yt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
      - run: npm i
      - run: node main.js
      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: ./outputs
