name: Create video

on:
  push:
    branches: [master]

jobs:
  create-video:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        sign: ["aries"]
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
      - run: npm i
      - run: node main.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: ./outputs
