name: Create video

on:
  push:
    branches: [master]

env:
  YT_UPLOADER_API: ${{ secrets.YT_UPLOADER_API }}

jobs:
  create-video:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        sign:
          [
            "aries",
            "taurus",
            "gemini",
            "cancer",
            "leo",
            "virgo",
            "libra",
            "scorpio",
            "sagittarius",
            "capricorn",
            "aquarius",
            "pisces",
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: Iamshankhadeep/setup-ffmpeg@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "5.0"
      - run: npm i
      - run: node main.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: ./outputs

  merge-videos:
    needs: create-video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: Iamshankhadeep/setup-ffmpeg@v1.2
        with:
          version: "5.0"
      - run: npm i
      - run: node merge.js
      - run: node upload.js
